# Generated by Django 2.1.3 on 2018-11-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='foto',
            field=models.ImageField(default='static/imagens/servicos/servicosImgTeste.jpg', upload_to='imagens/servicos', verbose_name='/static/'),
        ),
    ]
