# Generated by Django 2.1.3 on 2018-11-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181129_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='foto',
            field=models.ImageField(upload_to='servicos/'),
        ),
    ]
