# Generated by Django 2.1.3 on 2018-11-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181129_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='foto',
            field=models.ImageField(default='static/imagens/servicos/servicosImgTeste.jpg', upload_to='core/static/imagens/servicos'),
        ),
    ]
